
server:  
  port: ${PORT:8081}

instance.id: ${random.value}

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true #registra ip no hostname
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadata-map:
      instanceId: ${instance.id}

management:
  security:
    enabled: false #desactiva mecaniscos de actuator de spring

security:
  basic:
    enabled: false

spring:
  boot:
    admin:
      url: http://localhost:8090/
  datasource:
    driver-class-name: org.postgresql.Driver
    username: administrator
    password: S3cr#t4dm1n
    url: jdbc:postgresql://localhost:5432/social_network

  jpa:
    hibernate:
      ddlAuto: validate
      namingStrategy: org.hibernate.cfg.EJB3NamingStrategy
    show-sql: true

